1

In [ ]:
import numpy as np
STUDENT_NAME = "Kyla Daphnie Varde"
STUDENT_ID = 250753

np.random.seed(STUDENT_ID)
data = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
print(f"{STUDENT_NAME}'s Array:", data)

mean_val = np.mean(data)
std_val = np.std(data)
print("Mean:", mean_val, "\nStd Dev:", std_val)

Kyla Varde's Array: [ 74  30  16 101  59  38  12  31  79  76]
Mean: 51.6 
Std Dev: 28.73047162856886


2

In [17]:
import numpy as np
STUDENT_NAME = "Kyla Daphnie Varde"
STUDENT_ID = 250753

np.random.seed(STUDENT_ID)
matrix = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))
print(f"{STUDENT_NAME}'s Matrix:\n", matrix)

row_sums = np.sum(matrix, axis=1)
col_sums = np.sum(matrix, axis=0)
print("Row sums:", row_sums)
print("Column sums:", col_sums)

Kyla Daphnie Varde's Matrix:
 [[15 10 16  5]
 [12  6 12 19]
 [15 12 11 19]]
Row sums: [46 49 57]
Column sums: [42 28 39 43]


3

In [5]:
import numpy as np
STUDENT_NAME = "Daphnie Varde"
STUDENT_ID = 250753

np.random.seed(STUDENT_ID)
arr3d = np.random.randint(0, STUDENT_ID % 20 + 10, size=(3,3,3))
print(f"{STUDENT_NAME}'s 3D Array:\n", arr3d)

slice_mid = arr3d[:,1,:]
print("\nSlice[:,1,:]:\n", slice_mid)

Daphnie Varde's 3D Array:
 [[[14  9 15]
  [ 4 11  5]
  [11 18 14]]

 [[11 10 18]
  [ 7  8 21]
  [ 5  8  4]]

 [[12 16  3]
  [ 7 18  6]
  [20 13 13]]]

Slice[:,1,:]:
 [[ 4 11  5]
 [ 7  8 21]
 [ 7 18  6]]


4

In [6]:
import numpy as np
STUDENT_NAME = "Daphnie Varde"
STUDENT_ID = 250753

np.random.seed(STUDENT_ID)
x = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
filtered = x[(x>STUDENT_ID%50) & (x<STUDENT_ID%100)]
print(f"{STUDENT_NAME}'s Original:", x)
print("Filtered subset:", filtered)

Daphnie Varde's Original: [ 74  30  16 101  59  38  12  31  79  76]
Filtered subset: [30 16 38 12 31]


5

In [7]:
import numpy as np
STUDENT_NAME = "Kyla Varde"
STUDENT_ID = 250753

np.random.seed(STUDENT_ID)
A = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
B = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
print("Matrix A:\n", A)
print("Matrix B:\n", B)

product = A @ B
det_A = np.linalg.det(A)
print("A @ B:\n", product)
print("Determinant of A:", det_A)

Matrix A:
 [[15 10]
 [16  5]]
Matrix B:
 [[12  6]
 [12 19]]
A @ B:
 [[300 280]
 [252 191]]
Determinant of A: -85.00000000000001


6

In [12]:
import numpy as np
STUDENT_NAME = "Kyla Varde"
STUDENT_ID = 250753

angles = np.linspace(0, 2*np.pi, 8)
sine_vals = np.sin(angles)
cos_vals = np.cos(angles)
print(f"{STUDENT_NAME}'s Angles:\n", angles)
print("Sine:\n", sine_vals)
print("Cosine:\n", cos_vals)

Kyla Varde's Angles:
 [0.         0.8975979  1.7951958  2.6927937  3.5903916  4.48798951
 5.38558741 6.28318531]
Sine:
 [ 0.00000000e+00  7.81831482e-01  9.74927912e-01  4.33883739e-01
 -4.33883739e-01 -9.74927912e-01 -7.81831482e-01 -2.44929360e-16]
Cosine:
 [ 1.          0.6234898  -0.22252093 -0.90096887 -0.90096887 -0.22252093
  0.6234898   1.        ]


7

In [13]:
import numpy as np
STUDENT_NAME = "Kyla Varde"
STUDENT_ID = 250753

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(4,4))
arr[::2, ::2] = 0
print(f"{STUDENT_NAME}'s Modified 4x4 Array:\n", arr)

Kyla Varde's Modified 4x4 Array:
 [[ 0 10  0  5]
 [12  6 12 19]
 [ 0 12  0 19]
 [ 8  9 22  6]]


8

In [14]:
import numpy as np
STUDENT_NAME = "Kyla Varde"
STUDENT_ID = 250753

np.random.seed(STUDENT_ID)
scores = np.random.randint(0, STUDENT_ID % 100 + 50, 10)
grades = np.where(scores>=STUDENT_ID%70,'Pass','Fail')
print(f"{STUDENT_NAME}'s Scores:", scores)
print("Grades:", grades)

Kyla Varde's Scores: [ 73  29  15 100  58  37  11  30  78  75]
Grades: ['Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass' 'Pass']


9

In [15]:
import numpy as np
STUDENT_NAME = "Kyla Varde"
STUDENT_ID = 250753

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))
flat_arr = arr.flatten()
transposed_arr = arr.T
print("Original array:\n", arr)
print("Flattened:", flat_arr)
print("Transposed:\n", transposed_arr)

Original array:
 [[15 10 16  5]
 [12  6 12 19]
 [15 12 11 19]]
Flattened: [15 10 16  5 12  6 12 19 15 12 11 19]
Transposed:
 [[15 12 15]
 [10  6 12]
 [16 12 11]
 [ 5 19 19]]


10

In [19]:
import numpy as np
STUDENT_NAME = "Kyla Varde"
STUDENT_ID = 250753

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, (3,3))
mask = arr % 2 == 0
arr[mask] = -1
print("Array with conditional replacements:\n", arr)

Array with conditional replacements:
 [[15 -1 -1]
 [ 5 -1 -1]
 [-1 19 15]]


11

In [22]:
import numpy as np
import pandas as pd
STUDENT_NAME = "Kyla Varde"
STUDENT_ID = 250753

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
'Name': [STUDENT_NAME]*5,
'Score': np.random.randint(STUDENT_ID%50,
STUDENT_ID%100+50,5),
'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10,5)
})
print(df)

         Name  Score  YearsCodePro
0  Kyla Varde     76            11
1  Kyla Varde     32            18
2  Kyla Varde     18            14
3  Kyla Varde     61            11
4  Kyla Varde     40            10


12

In [23]:
import numpy as np
import pandas as pd
STUDENT_NAME = "Kyla Varde"
STUDENT_ID = 250753

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
'EdLevel': ['Bachelor','Master','PhD','Bachelor','Master'],
# Corrected to use a functional salary range, e.g., 40000 to 150000
'ConvertedComp': np.random.randint(40000, 150000, 5)
})
avg_salary = df.groupby('EdLevel')['ConvertedComp'].mean()
print(avg_salary)

EdLevel
Bachelor     51966.5
Master      101229.5
PhD         121609.0
Name: ConvertedComp, dtype: float64


13

In [24]:
import numpy as np
import pandas as pd
STUDENT_NAME = "Kyla Daphnie"
STUDENT_ID = 250753

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
'Country': ['Philippines','USA','UK','Canada','Germany'],
'ConvertedComp': np.random.randint(40000, 150000, 5)
})
top5 = df.sort_values(by='ConvertedComp', ascending=False)
print(top5)

       Country  ConvertedComp
1          USA         132279
2           UK         121609
4      Germany          70180
3       Canada          59471
0  Philippines          44462


14

In [25]:
import numpy as np
import pandas as pd
STUDENT_NAME = "Kyla Varde"
STUDENT_ID = 250753

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
'Name':[STUDENT_NAME]*5,
'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10,5)
})
high_exp = df[df['YearsCodePro']>STUDENT_ID%10]
print(high_exp)

         Name  YearsCodePro
0  Kyla Varde            14
1  Kyla Varde             9
2  Kyla Varde            15
3  Kyla Varde             4
4  Kyla Varde            11


15

In [26]:
import numpy as np
import pandas as pd

STUDENT_NAME = "Kyla Daphnie"
STUDENT_ID = 250753

np.random.seed(STUDENT_ID)
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000,
150000, 5)})
bins = [0, 50000, 100000, 150000, 200000]
labels = ['0-50k', '50-100k', '100-150k', '>150k']
df['Bracket'] = pd.cut(df['ConvertedComp'], bins=bins, labels=labels)
print(df)

   ConvertedComp   Bracket
0          44462     0-50k
1         132279  100-150k
2         121609  100-150k
3          59471   50-100k
4          70180   50-100k


16

In [28]:
import numpy as np
import pandas as pd
STUDENT_NAME = "Kyla Daphnie "
STUDENT_ID = 250753
np.random.seed(STUDENT_ID)
# Corrected Code: Using a functional salary range (40000 to 150000)
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000,
150000, 5)})
df['LogComp'] = np.log(df['ConvertedComp'])
print(df)

   ConvertedComp    LogComp
0          44462  10.702390
1         132279  11.792669
2         121609  11.708566
3          59471  10.993244
4          70180  11.158819


17

In [ ]:
import numpy as np
import pandas as pd
STUDENT_NAME = "Kyla Daphnie"
STUDENT_ID = 250753

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10, 5),
'ConvertedComp': np.random.randint(40000, 150000, 5)
})
corr_matrix = df.corr()
print(corr_matrix)

               YearsCodePro  ConvertedComp
YearsCodePro       1.000000      -0.479235
ConvertedComp     -0.479235       1.000000


18

In [31]:
import numpy as np
import pandas as pd
STUDENT_NAME = "Kyla Daphnie"
STUDENT_ID = 250753

np.random.seed(STUDENT_ID)

df = pd.DataFrame({
'EdLevel':['Bachelor','Master','PhD','Bachelor','Master'],
'ConvertedComp': np.random.randint(40000, 150000, 5)})
# Calculate mean, median, and standard deviation for each 'EdLevel'
summary = df.groupby('EdLevel')['ConvertedComp'].agg(['mean','median','std']).reset_index()
print(summary)

    EdLevel      mean    median           std
0  Bachelor   51966.5   51966.5  10612.965679
1    Master  101229.5  101229.5  43910.624005
2       PhD  121609.0  121609.0           NaN


19

In [32]:
import numpy as np
import pandas as pd
STUDENT_NAME = "Kyla Daphnie"
STUDENT_ID = 250753

np.random.seed(STUDENT_ID)

# Generate salaries: [100727, 136195, 130612, 100727, 95233]
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000, 150000, 5)})
threshold = 110000
# Create the 'HighPay' column using np.where()
df['HighPay'] = np.where(df['ConvertedComp'] > threshold, 'Yes', 'No')
print(df)

   ConvertedComp HighPay
0          44462      No
1         132279     Yes
2         121609     Yes
3          59471      No
4          70180      No


20

In [33]:
import numpy as np
import pandas as pd
STUDENT_NAME = "Kyla Daphnie"
STUDENT_ID = 250753

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
'Country': ['Philippines','USA','UK','Canada','Germany'],
'ConvertedComp': np.random.randint(40000, 150000, 5)})
# Group by 'Country' and calculate the mean and max 'ConvertedComp'
top_countries = df.groupby('Country')['ConvertedComp'].agg(['mean','max'])
print(top_countries)

                 mean     max
Country                      
Canada        59471.0   59471
Germany       70180.0   70180
Philippines   44462.0   44462
UK           121609.0  121609
USA          132279.0  132279
