1. Creating NumPy Arrays

In [8]:
# Step 1: Import NumPy
import numpy as np

# Step 2: Create a 1D array representing years of experience (Added 2 sample data points per Try It)
years_exp = np.array([1, 3, 5, 7, 10, 14, 19])
print("Years of Experience (1D Array):")
print(years_exp)

# Step 3: Create a 2D array representing sample salaries (in thousands) (Added 2 sample data points per Try It)
salaries = np.array([[50, 60, 70], [80, 90, 100], [67, 69, 71], [140, 180, 420]])
print("Salary Matrix (2D Array):")
print(salaries)

# Step 4: Create an array of zeros and ones for placeholder analysis
zeros_array = np.zeros((2, 2)) # 2x2 zeros
ones_array = np.ones((2, 3)) # 2x3 ones
print("Zeros Array:\n", zeros_array)
print("Ones Array:\n", ones_array) 

# Try It: 3x3 Identiy Matrix
identity_matrix = np.eye(3)
print("Identity Matrix (3x3):")
print(identity_matrix)

Years of Experience (1D Array):
[ 1  3  5  7 10 14 19]
Salary Matrix (2D Array):
[[ 50  60  70]
 [ 80  90 100]
 [ 67  69  71]
 [140 180 420]]
Zeros Array:
 [[0. 0.]
 [0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Identity Matrix (3x3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


2. Array Operations

In [ ]:
# Step 1: Element-wise addition
exp_plus_5 = years_exp + 5 # Add 5 years to all experience values
print("Years + 5:", exp_plus_5)

# Step 1: Element-wise subtraction as per Try It
exp_minus_5 = years_exp - 5 # Subtracted 5 years to all experience values
print("Years - 5:", exp_minus_5)

# Step 2: Element-wise multiplication
exp_times_2 = years_exp * 2 # Multiply all values by 2
print("Years * 2:", exp_times_2)

# Step 2: Element-wise division as per Try It
exp_div_2 = years_exp / 2 # Divided all values by 2
print("Years / 2:", exp_div_2)

# Step 3: Dot product (simulate salary projections)
sample1 = np.array([1, 2, 3])
sample2 = np.array([4, 5, 6])
dot_result = np.dot(sample1, sample2)
print("Dot Product:", dot_result)

# Try It: Applying np.exp() or np.log() on arrays
exp_values = np.exp(sample1) 
log_values = np.log(sample1)

print("Subtraction (Years - 1):", exp_minus_5)
print("Division (Years / 2):", exp_div_2)
print("Exponential (e^x on [1,2,3]):", exp_values)
print("Natural Log (ln on [1,2,3]):", log_values)


Years + 5: [ 6  8 10 12 15 19 24]
Years - 5: [-4 -2  0  2  5  9 14]
Years * 2: [ 2  6 10 14 20 28 38]
Years / 2: [0.5 1.5 2.5 3.5 5.  7.  9.5]
Dot Product: 32
Subtraction (Years - 1): [-4 -2  0  2  5  9 14]
Division (Years / 2): [0.5 1.5 2.5 3.5 5.  7.  9.5]
Exponential (e^x on [1,2,3]): [ 2.71828183  7.3890561  20.08553692]
Natural Log (ln on [1,2,3]): [0.         0.69314718 1.09861229]


3. Indexing and Slicing

In [23]:
# Step 1: Access individual element
print("First year of experience:", years_exp[0])

# Step 2: Slice arrays
print("First two salaries:", salaries[0, :2]) # First two elements of first row

# Step 3: Access all rows for a specific column
print("Second column salaries:", salaries[:, 1])

# Step 4: Negative indexing
print("Last year of experience:", years_exp[-1])

# Try It: Reverse arrays using slice
reversed_years = years_exp[::-1]
print("\nReversed years_exp:", reversed_years)

# Try It: Slice 2D arrays for subgroups of salaries 
salary_subgroup = salaries[0:2, 1:3]
print("Subgroup of salaries (2x2 slice):\n", salary_subgroup)

First year of experience: 1
First two salaries: [50 60]
Second column salaries: [ 60  90  69 180]
Last year of experience: 19

Reversed years_exp: [19 14 10  7  5  3  1]
Subgroup of salaries (2x2 slice):
 [[ 60  70]
 [ 90 100]]


4. Reshaping and Dimensions

In [26]:
# Step 1: Reshape 1D array into 2x3 matrix for batch analysis
reshaped_exp = np.reshape(np.arange(1, 7), (2, 3))
print("Reshaped Experience Array:\n", reshaped_exp)

# Step 2: Flatten 2D arrays back into 1D
flattened_exp = reshaped_exp.flatten()
print("Flattened Array:", flattened_exp)

# Step 3: Transpose example
print("Transposed Array:\n", reshaped_exp.T)

# Try It: Reshaping into different dimensions
try_it_3x2 = reshaped_exp.reshape(3, 2)
try_it_column = reshaped_exp.reshape(6, 1)

print("-" * 30)
print("Try It - 3x2 Reshape:\n", try_it_3x2)
print("\nTry It - 6x1 (Column Vector):\n", try_it_column)

Reshaped Experience Array:
 [[1 2 3]
 [4 5 6]]
Flattened Array: [1 2 3 4 5 6]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]
------------------------------
Try It - 3x2 Reshape:
 [[1 2]
 [3 4]
 [5 6]]

Try It - 6x1 (Column Vector):
 [[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


5. Broadcasting in NumPy

In [ ]:
# Step 1: Add a bonus array to salaries using broadcasting
bonus = np.array([5, 10, 15])
salaries_with_bonus = salaries + bonus # Adds corresponding bonus to each column
print("Salaries after bonus:\n", salaries_with_bonus)

# Try It: Multiply salaries by a scaling factor using broadcasting
scaling_factor = 0.6
scaled_salaries = salaries * scaling_factor

print("Scaled Salaries (60% Raise):\n", scaled_salaries)

Salaries after bonus:
 [[ 55  70  85]
 [ 85 100 115]
 [ 72  79  86]
 [145 190 435]]
Scaled Salaries (60% Raise):
 [[ 30.   36.   42. ]
 [ 48.   54.   60. ]
 [ 40.2  41.4  42.6]
 [ 84.  108.  252. ]]


6. Statistical Operations

In [31]:
# Step 1: Mean of years of experience
print("Mean experience:", np.mean(years_exp))

# Step 2: Standard deviation of experience
print("Std deviation of experience:", np.std(years_exp))

# Step 3: Max and Min salaries
print("Max salary:", np.max(salaries), "Min salary:", np.min(salaries))

# Step 4: Sum of salaries
print("Sum of all salaries:", np.sum(salaries))

# Try It: Compute median or percentiles for arrays
median_exp = np.median(years_exp)

percentile_25 = np.percentile(salaries, 25)
percentile_75 = np.percentile(salaries, 75)

print("Median experience:", median_exp)
print("25th Percentile of Salaries:", percentile_25)
print("75th Percentile of Salaries:", percentile_75)

Mean experience: 8.428571428571429
Std deviation of experience: 5.900536122303824
Max salary: 420 Min salary: 50
Sum of all salaries: 1397
Median experience: 7.0
25th Percentile of Salaries: 68.5
75th Percentile of Salaries: 110.0


7. NumPy Functions on Arrays

In [40]:
# Step 1: Apply trigonometric functions
angles = np.array([0, np.pi/4, np.pi/2])
print("Sine of angles:", np.sin(angles))
print("Cosine of angles:", np.cos(angles))

# Step 2: Apply function along rows (sum salaries per person)
salary_sums = np.apply_along_axis(np.sum, 1, salaries)
print("Sum of Salaries per person:", salary_sums)

# Try It: 
# Using np.sqrt() or np.log() for transformations
sqrt_salaries = np.sqrt(salaries)
log_salaries = np.log10(salaries)

# Applying custom functions with np.apply_along_axis()
def add_tax(row):
    return row * 0.80 

taxed_salaries = np.apply_along_axis(add_tax, 1, salaries)

print("\nSquare Root of Salaries:\n", sqrt_salaries)
print("\nSalaries after 20% Tax (Custom Function):\n", taxed_salaries)

Sine of angles: [0.         0.70710678 1.        ]
Cosine of angles: [1.00000000e+00 7.07106781e-01 6.12323400e-17]
Sum of Salaries per person: [180 270 207 740]

Square Root of Salaries:
 [[ 7.07106781  7.74596669  8.36660027]
 [ 8.94427191  9.48683298 10.        ]
 [ 8.18535277  8.30662386  8.42614977]
 [11.83215957 13.41640786 20.49390153]]

Salaries after 20% Tax (Custom Function):
 [[ 40.   48.   56. ]
 [ 64.   72.   80. ]
 [ 53.6  55.2  56.8]
 [112.  144.  336. ]]


8. Integrating NumPy and Pandas for Analysis

In [ ]:
import pandas as pd

# Step 1: Create a NumPy array of random data
data = np.random.randint(1, 50, size=(5, 3))

# Step 2: Convert the array into a DataFrame
df_data = pd.DataFrame(data, columns=['X', 'Y', 'Z'])
print("Generated Data:\n", df_data)

# Step 3: Apply NumPy functions to DataFrame columns
df_data['Log_X'] = np.log(df_data['X'])
df_data['Sqrt_Y'] = np.sqrt(df_data['Y'])
print("DataFrame with NumPy Transformations:\n", df_data)

# Step 4: Analyze data using Pandas correlation
print("Correlation Matrix:\n", df_data.corr())

# Try It:
#Use np.mean() and np.median() to compute overall column statistics
column_means = np.mean(df_data, axis=0)
column_medians = np.median(df_data, axis=0)

# 2. Apply other functions like np.square() or np.exp()
df_data['\Square_Z'] = np.square(df_data['Z'])
df_data['Exp_X_Small'] = np.exp(df_data['X'] / 10) 

print("\nColumn Means:\n", column_means)
print("\nColumn Medians:\n", column_medians)
print("\nFinal DataFrame with Square and Exp:\n", df_data)


Generated Data:
     X   Y   Z
0  49  23  38
1  46  25  29
2   3   4  16
3   9  24  26
4  13  19  48
DataFrame with NumPy Transformations:
     X   Y   Z     Log_X    Sqrt_Y
0  49  23  38  3.891820  4.795832
1  46  25  29  3.828641  5.000000
2   3   4  16  1.098612  2.000000
3   9  24  26  2.197225  4.898979
4  13  19  48  2.564949  4.358899
Correlation Matrix:
                X         Y         Z     Log_X    Sqrt_Y
X       1.000000  0.623763  0.315471  0.950195  0.605808
Y       0.623763  1.000000  0.511191  0.808753  0.997549
Z       0.315471  0.511191  1.000000  0.529856  0.567325
Log_X   0.950195  0.808753  0.529856  1.000000  0.803881
Sqrt_Y  0.605808  0.997549  0.567325  0.803881  1.000000

Column Means:
 X         24.000000
Y         19.000000
Z         31.400000
Log_X      2.716250
Sqrt_Y     4.210742
dtype: float64

Column Medians:
 [13.         23.         29.          2.56494936  4.79583152]

Final DataFrame with Square and Exp:
     X   Y   Z     Log_X    Sqrt_Y  \Square_

<>:24: SyntaxWarning: "\S" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\S"? A raw string is also an option.
<>:24: SyntaxWarning: "\S" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\S"? A raw string is also an option.
C:\Users\daphn\AppData\Local\Temp\ipykernel_10128\3003181916.py:24: SyntaxWarning: "\S" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\S"? A raw string is also an option.
  df_data['\Square_Z'] = np.square(df_data['Z'])


9. Importing and Summarizing Data Using Pandas

In [49]:
# Step 1: Save the DataFrame to a CSV file
df_data.to_csv('sample_data.csv', index=False)
print("Data saved to 'sample_data.csv'.")

# Step 2: Load the CSV file back into a new DataFrame
df_imported = pd.read_csv('sample_data.csv')
print("Imported DataFrame:\n", df_imported)

# Step 3: Generate summary statistics
summary_stats = df_imported.describe()
print("Summary Statistics:\n", summary_stats)

# Step 4: Display column means and standard deviations
print("Column Means:\n", df_imported.mean())
print("\nColumn Standard Deviations:\n", df_imported.std())

# Try It: Adding new calculated column and saving
df_imported['Sum_XY'] = df_imported['X'] + df_imported['Y']
df_imported.to_csv('modified_data.csv', index=False)
print("\nModified data saved to 'modified_data.csv'.")
print("\nNew Column 'Sum_XY' Preview:\n", df_imported[['X', 'Y', 'Sum_XY']].head())

Data saved to 'sample_data.csv'.
Imported DataFrame:
     X   Y   Z     Log_X    Sqrt_Y  \Square_Z  Exp_X_Small
0  49  23  38  3.891820  4.795832       1444   134.289780
1  46  25  29  3.828641  5.000000        841    99.484316
2   3   4  16  1.098612  2.000000        256     1.349859
3   9  24  26  2.197225  4.898979        676     2.459603
4  13  19  48  2.564949  4.358899       2304     3.669297
Summary Statistics:
                X          Y          Z     Log_X    Sqrt_Y    \Square_Z  \
count   5.000000   5.000000   5.000000  5.000000  5.000000     5.000000   
mean   24.000000  19.000000  31.400000  2.716250  4.210742  1104.200000   
std    21.771541   8.689074  12.157302  1.175629  1.259788   794.835958   
min     3.000000   4.000000  16.000000  1.098612  2.000000   256.000000   
25%     9.000000  19.000000  26.000000  2.197225  4.358899   676.000000   
50%    13.000000  23.000000  29.000000  2.564949  4.795832   841.000000   
75%    46.000000  24.000000  38.000000  3.828641  4.

10. Data Grouping and Aggregation

In [58]:
import pandas as pd
import numpy as np

# Step 1: Load the Stack Overflow 2023 Developer Survey dataset
try:
    df_kaggle = pd.read_csv('survey_results_public.csv')
    print("Loaded Dataset:\n", df_kaggle.head())
except FileNotFoundError:
    df_kaggle = pd.read_csv('sample_data.csv')
    print("Survey file not found. Using sample_data.csv as a placeholder.")

# Step 2: Select relevant columns
if 'Country' in df_kaggle.columns:
    target_cols = ['Country', 'EdLevel', 'YearsCodePro', 'ConvertedComp']
else:
    target_cols = ['X', 'Y', 'Z']
df_subset = df_kaggle[target_cols]
print("Subset of Data:\n", df_subset.head())

# Step 3: Clean the data by dropping rows with missing values
df_clean = df_subset.dropna()
print("Cleaned Data:\n", df_clean.head())

# Step 4: Categorize experience into groups
if 'YearsCodePro' in df_clean.columns:
    df_clean['YearsCodePro'] = pd.to_numeric(df_clean['YearsCodePro'], errors='coerce')
    df_clean = df_clean.dropna()
    df_clean['ExperienceLevel'] = np.where(df_clean['YearsCodePro'] >= 10, 'Senior', 'Junior')
else:
    df_clean['ExperienceLevel'] = np.where(df_clean['X'] >= 25, 'Senior', 'Junior')

# Step 5: Group data by Country and ExperienceLevel, compute average salary
group_by_col = 'Country' if 'Country' in df_clean.columns else 'Z'
value_col = 'ConvertedComp' if 'ConvertedComp' in df_clean.columns else 'Y'

# Step 6: Reset index for readability
grouped_data = df_clean.groupby([group_by_col, 'ExperienceLevel'])[value_col].mean().reset_index()
print("\nFormatted Grouped Data:\n", grouped_data.head())

# Try It:

# 1. Change grouping to EdLevel, Compute Median/Std
if 'EdLevel' in df_clean.columns:
    ed_stats = df_clean.groupby('EdLevel')['ConvertedComp'].agg(['median', 'std']).reset_index()
    print("\nEducation Stats (Median & Std):\n", ed_stats)

# 2. Explore top 10 countries with highest average compensation
if 'Country' in df_clean.columns:
    top_10 = grouped_data.groupby('Country')[value_col].mean().sort_values(ascending=False).head(10)
    print("\nTop 10 Highest Paying Countries:\n", top_10)

Survey file not found. Using sample_data.csv as a placeholder.
Subset of Data:
     X   Y   Z
0  49  23  38
1  46  25  29
2   3   4  16
3   9  24  26
4  13  19  48
Cleaned Data:
     X   Y   Z
0  49  23  38
1  46  25  29
2   3   4  16
3   9  24  26
4  13  19  48

Formatted Grouped Data:
     Z ExperienceLevel     Y
0  16          Junior   4.0
1  26          Junior  24.0
2  29          Senior  25.0
3  38          Senior  23.0
4  48          Junior  19.0
